routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/tentangkami', 'HomeController@aboutus')->name('aboutus');
Route::get('/post/detail/{id}', 'HomeController@post_detail')->name('post.detail');
Route::get('/tempat', 'HomeController@place')->name('place');
Route::get('/acara', 'HomeController@event')->name('event');
Route::get('/berita', 'HomeController@news')->name('news');
Route::get('/komunitas', 'HomeController@community')->name('community');
Route::get('/komunitas/{id}', 'HomeController@community_detail')->name('community.detail');
Route::get('/tempat/{id}', 'HomeController@place_detail')->name('place.detail');
Route::get('/berita/{id}', 'HomeController@news_detail')->name('news.detail');
Route::get('/acara/{id}', 'HomeController@event_detail')->name('event.detail');
Route::post('/content/based', 'User\HomeController@content_based_post')->name('user.content.based.post');

Route::group(array('prefix' => 'admin'), function () {
  Route::get('/dashboard', 'Admin\DashboardController@index')->name('admin.dashboard');
  Route::get('/method', 'HomeController@method')->name('admin.method');
  Route::resource('/dashboard/berita', 'Admin\BeritaController', ['as' => 'admin'])->except([
      'show'
  ]);
});

Route::group(array('prefix' => 'user'), function () {
  Route::get('/dashboard', 'User\Dashboard\DashboardController@index')->name('user.dashboard');
  Route::resource('/dashboard/tempat', 'User\TempatController',  ['as' => 'user'])->except([
      'show'
  ]);
  Route::resource('/dashboard/acara', 'User\AcaraController',  ['as' => 'user'])->except([
      'show'
  ]);
  Route::resource('/dashboard/komunitas', 'User\KomunitasController',  ['as' => 'user'])->except([
      'show'
  ]);
  Route::resource('/ulasan', 'User\UlasanController', ['as' => 'user'])->except([
      'show', 'index', 'create', 'edit'
  ]);
  Route::get('/dashboard/profile', 'User\Dashboard\DashboardProfileController@index')->name('user.profile');
  Route::resource('/dashboard/hobby', 'User\Dashboard\MyHobbyController', ['as' => 'user'])->except([
      'show'
  ]);
});

resources/views/acara.blade.php
@extends('layouts.app')

@section('style')
<style>

</style>
@stop

@section('content')
<div class="page-tours bg-header page-tours-grid-3-left pd-tour">
	<div class="container">
		<div class="breadcrumbs-container">
		  <ul class="breadcrumbs min-list inline-list">
		    <li class="breadcrumbs__item">
		      <a href="index.html" class="breadcrumbs__link">
		        <span class="breadcrumbs__title">Home</span>
		      </a>
		    </li>
		    <li class="breadcrumbs__item">
		      <span class="breadcrumbs__page c-gray">Acara</span>
		    </li>
		  </ul><!-- .breadcrumbs -->
		</div>
		<h1 class="title__page">Acara</h1>
		<div class="header-form">
      <form action="#">
				<div class="form-search d-lg-flex form-search__home1">
					<div class="form-iner-2 p-rt">
						<input class="input-home search-info" type="text" name="text" placeholder="Cari Yang Sesui Hobi Kamu ...">
					</div>
					<div class="form-iner form-submit__home1">
						<button type="submit" class="btn-submit button-home">Search now</button>
					</div>
				</div>
			</form>
		</div>
		<div class="row">
      <div class="col-lg-3">
        <aside class="sidebar widget-sidebar">
          <section class="widget widget-list-tours">
            <h3 class="widget-title">Sort By</h3>
            <div class="widget-main-select">
              <div class="squaredcheck">
                <input type="radio" value="None" id="squaredcheck" class="checkbox1" name="check" checked />
                <label for="squaredcheck"><span class="main-listing__form-label">Recommended</span></label>
              </div>
              <div class="squaredcheck">
                <input type="radio" value="None" id="squaredcheck1" class="checkbox1" name="check"  />
                <label for="squaredcheck1"><span class="main-listing__form-label">Newest</span></label>
              </div>
              <div class="squaredcheck">
                <input type="radio" value="None" id="squaredcheck2" class="checkbox1" name="check"/>
                <label for="squaredcheck2"><span class="main-listing__form-label">Likes</span></label>
              </div>
              <div class="squaredcheck">
                <input type="radio" value="None" id="squaredcheck3" class="checkbox1" name="check" />
                <label for="squaredcheck3"><span class="main-listing__form-label">Rating</span></label>
              </div>
            </div>
          </section>
          <section class="widget widget-list-tours">
            <h3 class="widget-title">Hobby</h3>
            <ul>
              <li>
                @foreach(App\Hobby::get() as $item)
                <a href="#">
                  <span>{{$item->nama}}</span>
                  <span class="main-listing__form-desc">({{rand(0,10)}})</span>
                </a>
                @endforeach
              </li>
            </ul>
          </section>
          <!-- end-widget -->
        </aside>
      </div>
			<!-- end-col -->
      <div class="col-lg-9">
        <div class="row">
          <div class="col-md-12 listing-search-container d-lg-flex">
            <div class="listing-view">
              <span class="c-dusty-gray">Showing 1-12 of 135 tours</span>
            </div>
          </div>
					@foreach($acara as $item)
          <!-- end-col -->
          <div class="col-md-4">
            <div class="listing__wrapper">
              <div class="listing__thubmail">
                <a href="tour-single.html">
                  <div class="item-grid__image-overlay"></div>
                  <img src="{{asset('images/contents/'.$item->gambar)}}" style="width:100%;height:200px" alt="tours">
                </a>
                <div class="listing__favorite">
                  <span class="wishlist-img btn-radius ion-images"></span>
                  <span class="wishlist-img btn-radius ion-ios-heart-outline"></span>
                </div>
              </div>
              <div class="listing_detail">
                <h3><a href="{{route('event.detail', $item->id)}}" class="listing__title">{{substr($item->judul,0,20)}} ...</a></h3>
                <div class="listing__review">
                  <ul class="min-list inline-list list-meta">
                    <li class="review-dots">Rating : <span class="review__start img-sale" style="width:10%;height:10%">0</span></li>
                    <li><span class="d-review"> Likes <span class="c-green">0</span></span></li>
                  </ul>
                </div>
                <div class="listing-entry__meta">
                  <span class="entry__location"><i class="fa fa-sun"></i> {{$item->hobi}}</span>
                </div>
              </div>
            </div>
          </div>
          <!-- end-col -->
					@endforeach
        </div>
        <!-- end-row -->
      </div>
			<!-- end-col -->
		</div>
		<!-- end-row -->

	</div>
	<!-- end-container -->
</div>
@endsection

@section('script')
<script>
</script>
@stop

resources/views/acara_detail.blade.php
@extends('layouts.app')

@section('style')
<style>

</style>
@stop

@section('content')
<div class="main-content-single content-slider-single">
	<div class="container">
		<div class="row">
			<div class="col-lg-8">
				<div class="content-area"  style="margin-bottom:50px">
					<section class="page-banner">
						<div class="post_page_blog-sidebar">
							<h2 class="title-single-sidebar">{{$acaraDetail->judul}}</h2>
							<div class="post-socical">
								<ul class="min-list inline-list">
									<li class="menu-item">
										 <img class="item-thubmail-2" src="{{asset('assets/image/uploads/id-bl.png')}}" alt="id"><span class="socical-title">{{$acaraDetail->user->name}}</span>
									</li>
									<li class="menu-item">
										<img class="item-thubmail" src="{{asset('assets/image/bl-date.png')}}" alt="id"><span class="socical-title">{{date('D M Y',strtotime($acaraDetail->created_at))}}</span>
									</li>
									<li class="menu-item">
										<img class="item-thubmail" src="{{asset('assets/image/bl-cm.png')}}" alt="id"><span class="socical-title">{{$acaraDetail->ulasan->count()}}</span>
									</li>
									<li class="menu-item">
										#<span class="socical-title" style="margin:0">{{$acaraDetail->type}}</span>
									</li>
								</ul>
							</div>
						</div>
					</section>
					<div class="post-blog__single">
						<div class="post-blog__image">
							<img src="{{asset('images/contents/'.$acaraDetail->gambar)}}" style="width:100%;height:400px" alt="tours">
						</div>
						<div class="">
							<div class="entry-header">
								<h2 class="entry-header__title">{{$acaraDetail->judul}}</h2>
							</div>
							<div class="entry-content">
								{!!$acaraDetail->deskripsi!!}
							</div>
							<div class="entry-meta d-md-flex justify-content-md-between">
								<div class="entry-tags">
									<span class="tags-title">Hobi:</span>
									@foreach(explode(',', $acaraDetail->hobi) as $item)
									<a href="#">{{$item}} | </a>
									@endforeach
								</div>
							</div>
						</div>
					</div>
					<div class="comment-single bg-white" style="padding:20px">
						<nav class="listing-nav collapse navbar-collapse" id="myNavbar">
							<ul class="min-list inline-list">
								<li>
									<a class="listing-nav-link nav-link" href="#review">Reviews</a>
								</li>
								@if(Auth::user())
								<li>
									<a class="listing-nav-link nav-link" href="#write">Write a review</a>
								</li>
								@endif
							</ul>
						</nav>
						<!-- end-nav -->
						<section class="list-comment_wrapper listing-section__single" id="review">
							<ul class="min-list">
								@foreach($ulasan as $item)
								<li>
									<div class="list-comment__Wrapper d-flex bd-bottom first-comment">
										<!-- <div class="img-thubmail">
											<img src="{{asset('assets/image/uploads/id-comment.png')}}" alt="tours">
										</div> -->
										<div class="comment_detail">
											<h4 class="entry-title__comment">{{$item->user->name}} {{$item->id_user == Auth::user()->id ? '(Yours)' : ''}}</h4>
											<span class="entry-time"> {{$acaraDetail->created_at}}</span>
											<p class="entry-description">{{$item->deskripsi}}</p>
											<div class="comment-star" style="max-width:200px">
												<span>Rating:</span>
												<span>
													@for($i=0;$i<$item->rating;$i++)
													<i class="ion-ios-star"></i>
													@endfor
													@for($i=0;$i<(5-($item->rating));$i++)
													<i class="ion-ios-star" style="color:#dddddd"></i>
													@endfor
												</span>
											</div>
										</div>
									</div>
								</li>
								@endforeach
							</ul>
						</section>
							<!-- end-comment -->
							<div class="pagination_tours-reviews d-flex justify-content-center pagination_blog">
								{{$ulasan->links()}}
							</div>
							<!-- end-pagination -->

							<section class="form-comment listing-section__single" id="write">
								@if(Auth::user())
									@if($acaraDetail->ulasan->where('id_user', Auth::user()->id)->count() > 0)
									@php($ulasanUser = $acaraDetail->ulasan->where('id_user', Auth::user()->id)->first())
									<div class="wrap-rating in-post">
										<div class="form-group">
											<div class="head" style="display:flex">
												<h4 class="form-label">Edit Your Review :</h4>
												<button class="btn-radius btn-submit" onclick="$('#delete-ul').submit()" style="padding:7px;position:absolute;right:75px">Hapus Ulasan</button>
												<form id="delete-ul" action="{{route('user.ulasan.destroy', $ulasanUser->id)}}" method="post">
													@method('DELETE')
													@csrf
												</form>
											</div>
											<ul class="min-list inline-list stars">
												<li class="star" id="rating-1" data-rating="1" onclick="$('#rating').val(1)">
													<i class="ion-ios-star"></i>
												</li>
												<li class="star" id="rating-2" data-rating="2" onclick="$('#rating').val(2)">
													<i class="ion-ios-star"></i>
												</li>
												<li class="star" id="rating-3" data-rating="3" onclick="$('#rating').val(3)">
													<i class="ion-ios-star"></i>
												</li>
												<li class="star" id="rating-4" data-rating="4" onclick="$('#rating').val(4)">
													<i class="ion-ios-star"></i>
												</li>
												<li class="star" id="rating-5" data-rating="5" onclick="$('#rating').val(5)">
													<i class="ion-ios-star"></i>
												</li>
											</ul>
										</div>
									</div>
									<form action="{{route('user.ulasan.update', $ulasanUser->id)}}" method="post">
										@method('PUT')
										@csrf
										<input type="hidden" name="content_id" value="{{$acaraDetail->id}}">
										<input type="hidden" id="rating" name="rating" value="{{$ulasanUser->rating}}">
										<div class="form-comment">
											<label class="title-form" for="comment" >Your review <span class="c-sale">*</span></label>
											<textarea name="comment" class="form-area input-border" id="comment">{{$ulasanUser->deskripsi}}</textarea>
										</div>
										<div class="form-submit">
											<button type="submit" class="btn-radius btn-submit">Submit</button>
										</div>
									</form>
									@else
									<div class="wrap-rating in-post">
										<div class="form-group">
											<h4 class="form-label">Choose your rate :</h4>
											<ul class="min-list inline-list stars">
												<li class="star" data-rating="1" onclick="$('#rating').val(1)">
													<i class="ion-ios-star"></i>
												</li>
												<li class="star" data-rating="2" onclick="$('#rating').val(2)">
													<i class="ion-ios-star"></i>
												</li>
												<li class="star" data-rating="3" onclick="$('#rating').val(3)">
													<i class="ion-ios-star"></i>
												</li>
												<li class="star" data-rating="4" onclick="$('#rating').val(4)">
													<i class="ion-ios-star"></i>
												</li>
												<li class="star" data-rating="5" onclick="$('#rating').val(5)">
													<i class="ion-ios-star"></i>
												</li>
											</ul>
										</div>
									</div>
									<form action="{{route('user.ulasan.store')}}" method="post">
										@csrf
										<input type="hidden" name="content_id" value="{{$acaraDetail->id}}">
										<input type="hidden" id="rating" name="rating" value="0">
										<div class="form-comment">
											<label class="title-form" for="comment" >Your review <span class="c-sale">*</span></label>
											<textarea name="comment" class="form-area input-border" id="comment"></textarea>
										</div>
										<div class="form-submit">
											<button type="submit" class="btn-radius btn-submit">Submit</button>
										</div>
									</form>
									@endif
								@else
								<div class="text-center" style="text-align:center">
									<h2><a href="{{route('login')}}">Login</a> Terlebih Dahulu Untuk Memberi Ulasan</h2>
								</div>
								@endif
							</section>
							<!-- end-form-comment -->
						<!-- end-review -->
					</div>
				</div>
			</div>
			<div class="col-lg-4">
				<div class="sidebar widget-area">
					<section class="widget widget-sale">
						<div class="price-form">
							<!-- <span class="price-form__step"> Tersedia <i class="fa fa-info-circle" aria-hidden="true"></i></span> -->
							<div class="to">
								<span class="price-form__step"> Tersedia <i class="fa fa-check" aria-hidden="true"></i></span>
								<span style="float:right" class="price-form__step"> {{date('D M Y',strtotime($acaraDetail->updated_at))}}</span>
							</div>
							<div class="price-form__price-list" style="display: block;">
								<h1 class="title__page price__wrap">Rp. {{number_format($acaraDetail->acara->biaya)}}</h1>
								<p style="font-size: 14px;color: #f4b9c3;    font-weight: bold;">{{$acaraDetail->acara->catatan_biaya}}</p>
								<!-- <span class="price__warapper">$530</span> -->
							</div>
						</div>
					</section>
					<section class="widget widget-form bg-white" style="text-align:center">
						@guest
						<h3><a href="{{route('login')}}">Login</a> Untuk Memesan Acara</h3>
						@else
						<form action="http://haintheme.com/">
							<div class="form-submit">
								<button class="btn-submit btn-radius button-submit">Pesan Sekarang</button>
							</div>
						</form>
						@endif
					</section>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

@section('script')
<script>
function rating(id){
	$('#rating-'+id).click();
}

$('.pagination').addClass('min-list inline-list bg-navigation')
$('.pagination li').first().children().text('').addClass('ion-ios-arrow-back');
$('.pagination li').last().children().text('').addClass('ion-ios-arrow-forward');
var text = $('.pagination').find('.active').children().text();
$('.pagination').find('.active').children().replaceWith('<a class="page-link">'+text+'</a>');
</script>
@if(Auth::user())
	@if($acaraDetail->ulasan->where('id_user', Auth::user()->id)->count() > 0)
	<script>
	rating({{$acaraDetail->ulasan->where('id_user', Auth::user()->id)->first()->rating}});
	</script>
	@endif
@endif
@stop

resources/views/berita_detail.blade.php
@extends('layouts.app')

@section('style')
<style>

</style>
@stop

@section('content')
<div class="main-content-single content-slider-single">
	<div class="container">
		<div class="row">
			<div class="col-lg-8">
				<div class="content-area"  style="margin-bottom:50px">
					<section class="page-banner">
						<div class="post_page_blog-sidebar">
							<h2 class="title-single-sidebar">{{$beritaDetail->judul}}</h2>
							<div class="post-socical">
								<ul class="min-list inline-list">
									<li class="menu-item">
										 <img class="item-thubmail-2" src="{{asset('assets/image/uploads/id-bl.png')}}" alt="id"><span class="socical-title">{{$beritaDetail->user->name}}</span>
									</li>
									<li class="menu-item">
										<img class="item-thubmail" src="{{asset('assets/image/bl-date.png')}}" alt="id"><span class="socical-title">{{date('D M Y',strtotime($beritaDetail->created_at))}}</span>
									</li>
									<li class="menu-item">
										<img class="item-thubmail" src="{{asset('assets/image/bl-cm.png')}}" alt="id"><span class="socical-title">{{$beritaDetail->ulasan->count()}}</span>
									</li>
								</ul>
							</div>
						</div>
					</section>
					<div class="post-blog__single">
						<div class="post-blog__image">
							<img src="{{asset('images/contents/'.$beritaDetail->gambar)}}" style="width:100%;height:400px" alt="tours">
						</div>
						<div class="">
							<div class="entry-header">
								<h2 class="entry-header__title">{{$beritaDetail->judul}}</h2>
							</div>
							<div class="entry-content">
								{!!$beritaDetail->deskripsi!!}
							</div>
							<div class="entry-meta d-md-flex justify-content-md-between">
								<div class="entry-tags">
									<span class="tags-title">Hobi:</span>
									@foreach(explode(',', $beritaDetail->hobi) as $item)
									<a href="#">{{$item}} | </a>
									@endforeach
								</div>
							</div>
						</div>
					</div>
					<div class="comment-single bg-white" style="padding:20px">
						<nav class="listing-nav collapse navbar-collapse" id="myNavbar">
							<ul class="min-list inline-list">
								<li>
									<a class="listing-nav-link nav-link" href="#review">Reviews</a>
								</li>
								<li>
									<a class="listing-nav-link nav-link" href="#write">Write a review</a>
								</li>
							</ul>
						</nav>
						<!-- end-nav -->
						<section class="list-comment_wrapper listing-section__single" id="review">
							<ul class="min-list">
								@foreach($ulasan as $item)
								<li>
									<div class="list-comment__Wrapper d-flex bd-bottom first-comment">
										<!-- <div class="img-thubmail">
											<img src="{{asset('assets/image/uploads/id-comment.png')}}" alt="tours">
										</div> -->
										<div class="comment_detail">
											<h4 class="entry-title__comment">{{$item->user->name}} {{$item->id_user == Auth::user()->id ? '(Yours)' : ''}}</h4>
											<span class="entry-time"> {{$beritaDetail->created_at}}</span>
											<p class="entry-description">{{$item->deskripsi}}</p>
											<div class="comment-star" style="max-width:200px">
												<span>Rating:</span>
												<span>
													@for($i=0;$i<$item->rating;$i++)
													<i class="ion-ios-star"></i>
													@endfor
													@for($i=0;$i<(5-($item->rating));$i++)
													<i class="ion-ios-star" style="color:#dddddd"></i>
													@endfor
												</span>
											</div>
										</div>
									</div>
								</li>
								@endforeach
							</ul>
						</section>
							<!-- end-comment -->
							<div class="pagination_tours-reviews d-flex justify-content-center pagination_blog">
								{{$ulasan->links()}}
							</div>
							<!-- end-pagination -->

							<section class="form-comment listing-section__single" id="write">
								@if(Auth::user())
									@if($beritaDetail->ulasan->where('id_user', Auth::user()->id)->count() > 0)
									@php($ulasanUser = $beritaDetail->ulasan->where('id_user', Auth::user()->id)->first())
									<div class="wrap-rating in-post">
										<div class="form-group">
											<div class="head" style="display:flex">
												<h4 class="form-label">Edit Your Review :</h4>
												<button class="btn-radius btn-submit" onclick="$('#delete-ul').submit()" style="padding:7px;position:absolute;right:75px">Hapus Ulasan</button>
												<form id="delete-ul" action="{{route('user.ulasan.destroy', $ulasanUser->id)}}" method="post">
													@method('DELETE')
													@csrf
												</form>
											</div>
											<ul class="min-list inline-list stars">
												<li class="star" id="rating-1" data-rating="1" onclick="$('#rating').val(1)">
													<i class="ion-ios-star"></i>
												</li>
												<li class="star" id="rating-2" data-rating="2" onclick="$('#rating').val(2)">
													<i class="ion-ios-star"></i>
												</li>
												<li class="star" id="rating-3" data-rating="3" onclick="$('#rating').val(3)">
													<i class="ion-ios-star"></i>
												</li>
												<li class="star" id="rating-4" data-rating="4" onclick="$('#rating').val(4)">
													<i class="ion-ios-star"></i>
												</li>
												<li class="star" id="rating-5" data-rating="5" onclick="$('#rating').val(5)">
													<i class="ion-ios-star"></i>
												</li>
											</ul>
										</div>
									</div>
									<form action="{{route('user.ulasan.update', $ulasanUser->id)}}" method="post">
										@method('PUT')
										@csrf
										<input type="hidden" name="content_id" value="{{$beritaDetail->id}}">
										<input type="hidden" id="rating" name="rating" value="{{$ulasanUser->rating}}">
										<div class="form-comment">
											<label class="title-form" for="comment" >Your review <span class="c-sale">*</span></label>
											<textarea name="comment" class="form-area input-border" id="comment">{{$ulasanUser->deskripsi}}</textarea>
										</div>
										<div class="form-submit">
											<button type="submit" class="btn-radius btn-submit">Submit</button>
										</div>
									</form>
									@else
									<div class="wrap-rating in-post">
										<div class="form-group">
											<h4 class="form-label">Choose your rate :</h4>
											<ul class="min-list inline-list stars">
												<li class="star" data-rating="1" onclick="$('#rating').val(1)">
													<i class="ion-ios-star"></i>
												</li>
												<li class="star" data-rating="2" onclick="$('#rating').val(2)">
													<i class="ion-ios-star"></i>
												</li>
												<li class="star" data-rating="3" onclick="$('#rating').val(3)">
													<i class="ion-ios-star"></i>
												</li>
												<li class="star" data-rating="4" onclick="$('#rating').val(4)">
													<i class="ion-ios-star"></i>
												</li>
												<li class="star" data-rating="5" onclick="$('#rating').val(5)">
													<i class="ion-ios-star"></i>
												</li>
											</ul>
										</div>
									</div>
									<form action="{{route('user.ulasan.store')}}" method="post">
										@csrf
										<input type="hidden" name="content_id" value="{{$beritaDetail->id}}">
										<input type="hidden" id="rating" name="rating" value="0">
										<div class="form-comment">
											<label class="title-form" for="comment" >Your review <span class="c-sale">*</span></label>
											<textarea name="comment" class="form-area input-border" id="comment"></textarea>
										</div>
										<div class="form-submit">
											<button type="submit" class="btn-radius btn-submit">Submit</button>
										</div>
									</form>
									@endif
								@else
								<div class="text-center" style="text-align:center">
									<h2><a href="{{route('login')}}">Login</a> Terlebih Dahulu Untuk Memberi Ulasan</h2>
								</div>
								@endif
							</section>
							<!-- end-form-comment -->
						<!-- end-review -->
					</div>
				</div>
			</div>
			<div class="col-lg-4">
				<div class="sidebar-blog  content-area">
					<div class="list-content-sidebar">
						<form action="#" class="form-search-sidebar">
							<div class="search-sidebar">
								<input class="input-form input-border" type="text" name="text" placeholder="Enter keyword...">
								<button class="submit-search"><img src="{{asset('assets/image/search.png')}}" alt="button"></button>
							</div>
						</form>
						<div class="siderbar-post">
							<h3 class="widget-title">Recent Post</h3>
							<ul class="min-list list-sidebar">
								@foreach($berita as $item)
								<li><a href="#">{{$item->judul}}</a></li>
								@endforeach
							</ul>
						</div>
						<div class="sidebar-tags">
							<h3 class="widget-title">Hobi</h3>
							@foreach($hobby as $item)
							<a href="#">{{$item->nama}} | </a>
							@endforeach
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

@section('script')
<script>
function rating(id){
	$('#rating-'+id).click();
}

$('.pagination').addClass('min-list inline-list bg-navigation')
$('.pagination li').first().children().text('').addClass('ion-ios-arrow-back');
$('.pagination li').last().children().text('').addClass('ion-ios-arrow-forward');
var text = $('.pagination').find('.active').children().text();
$('.pagination').find('.active').children().replaceWith('<a class="page-link">'+text+'</a>');
</script>
@if(Auth::user())
	@if($beritaDetail->ulasan->where('id_user', Auth::user()->id)->count() > 0)
	<script>
	rating({{$beritaDetail->ulasan->where('id_user', Auth::user()->id)->first()->rating}});
	</script>
	@endif
@endif
@stop

resources/views/tentang_kami.blade.php
@extends('layouts.app')

@section('style')
<style>

</style>
@stop

@section('content')
<section class="page-banner bg-header page-banner--layout-blog__modem">
	<div class="header-title_about container">
	</div>
</section>
<div class="page-about">
	<section class="section-about section-head">
		<div class="container">
			<div class="entry-top d-flex">
				<div class="entry-top__wrap">
					<h1 class="entry-title">Tentang Kami</h1>
				</div>
			</div>
			<div class="entry-bottom">
				<div class="row">
					<div class="col-md-12 section-about section-content  bg-header">
						<div class="intro-video">
							<div class="intro-video__wrapper">
								<h2 class="entry-title">Our Story</h2>
								<h3>Suspendisse gravida elementum lacus, amae suada tortor sollicitudin ut. Donec pharetra metus lectus, ut eleifend eros sol licitu din.</h3>
								<p>Proin maximus ut augue ut finibus. In non est eu libero rutrum fringilla. Mauris dictum, turpis in convallis tincidunt, est dui varius est, eget ultrices magna quam eu tellus.</p>
								<p>Maecenas pellentesque aliquet arcu, vel elementum magna facilisis vitae. Nam in cursus lorem. </p>
								<p>Donec ac tellus nisl. Sed vo lutpat quis orci nec placerat fusce ex magna. Quisque venenatis, eros in auctor dictum, ipsum nisi imperdiet sem, at pulvinar nisl ante id sem.</p>
							</div>
						</div>
					</div>
					<!-- end-col -->
				</div>
				<!-- end-row -->
			</div>
		</div>
		<!-- end-container -->
	</section>
</div>
@stop

@section('script')
<script>
$(document).ready(function(){

});
</script>
@stop