routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/tentangkami', 'HomeController@aboutus')->name('aboutus');
Route::get('/post/detail/{id}', 'HomeController@post_detail')->name('post.detail');
Route::get('/tempat', 'HomeController@place')->name('place');
Route::get('/acara', 'HomeController@event')->name('event');
Route::get('/berita', 'HomeController@news')->name('news');
Route::get('/komunitas', 'HomeController@community')->name('community');
Route::get('/komunitas/{id}', 'HomeController@community_detail')->name('community.detail');
Route::get('/tempat/{id}', 'HomeController@place_detail')->name('place.detail');
Route::get('/berita/{id}', 'HomeController@news_detail')->name('news.detail');
Route::get('/acara/{id}', 'HomeController@event_detail')->name('event.detail');
Route::post('/content/based', 'User\HomeController@content_based_post')->name('user.content.based.post');

Route::group(array('prefix' => 'admin'), function () {
  Route::get('/dashboard', 'Admin\DashboardController@index')->name('admin.dashboard');
  Route::get('/method', 'HomeController@method')->name('admin.method');
  Route::resource('/dashboard/berita', 'Admin\BeritaController', ['as' => 'admin'])->except([
      'show'
  ]);
});

Route::group(array('prefix' => 'user'), function () {
  Route::get('/dashboard', 'User\Dashboard\DashboardController@index')->name('user.dashboard');
  Route::resource('/dashboard/tempat', 'User\TempatController',  ['as' => 'user'])->except([
      'show'
  ]);
  Route::resource('/dashboard/acara', 'User\AcaraController',  ['as' => 'user'])->except([
      'show'
  ]);
  Route::resource('/dashboard/komunitas', 'User\KomunitasController',  ['as' => 'user'])->except([
      'show'
  ]);
  Route::resource('/ulasan', 'User\UlasanController', ['as' => 'user'])->except([
      'show', 'index', 'create', 'edit'
  ]);
  Route::get('/dashboard/profile', 'User\Dashboard\DashboardProfileController@index')->name('user.profile');
  Route::resource('/dashboard/hobby', 'User\Dashboard\MyHobbyController', ['as' => 'user'])->except([
      'show'
  ]);
});

app/Http/Controllers/Admin/DashboardController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\BukuAnggaran;
use App\ContentBased;
use App\Hobby;
use App\Jobs\CBA;

class DashboardController extends AdminController
{
    public function index(){
      $content = ContentBased::limit(4)->get();
      $hobby = Hobby::get();

      return view('admin.dashboard', compact('hobby', 'content'));
    }
}

app/Http/Controllers/User/Dashboard/BeritaController.php
<?php

namespace App\Http\Controllers\User\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Controllers\User\UserController;
use App\Hobby;
use App\UserProfile;
use Auth;

class BeritaController extends UserController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $userProfile = UserProfile::where('id_user', Auth::user()->id)->first();
      $userHobby = [];
      if($userProfile){
        $userHobby = explode(',', $userProfile->hobby);
      }

      $hobby = Hobby::whereNotIn('nama', $userHobby)->get();
      $hobbyUser = Hobby::whereIn('nama', $userHobby)->get();

      return view('user.dashboard.berita.index', compact('userProfile', 'hobbyUser', 'hobby'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      $hobby = Hobby::get();

      return view('user.dashboard.berita.create', compact('hobby'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        dd($request);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/User/Dashboard/DashboardAcaraController.php
<?php

namespace App\Http\Controllers\User\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardAcaraController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/User/Dashboard/DashboardBeritaController.php
<?php

namespace App\Http\Controllers\User\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardBeritaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/User/Dashboard/DashboardController.php
<?php

namespace App\Http\Controllers\User\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {


        return view('user.dashboard.dashboard');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/User/Dashboard/DashboardKomunitasController.php
<?php

namespace App\Http\Controllers\User\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardKomunitasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/User/Dashboard/DashboardProfileController.php
<?php

namespace App\Http\Controllers\User\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Controllers\User\UserController;
use App\Hobby;
use App\UserProfile;
use Auth;

class DashboardProfileController extends UserController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $userProfile = UserProfile::where('id_user', Auth::user()->id)->first();
      $userHobby = [];
      if($userProfile){
        $userHobby = explode(',', $userProfile->hobby);
      }

      $hobby = Hobby::whereNotIn('nama', $userHobby)->get();

      return view('user.dashboard.profile', compact('userProfile', 'userHobby', 'hobby'));
    }

    /**
     *  Store a newly created resource in storage.
     *
     * @return \Illuminate\Http\Response
     */
    public function add_hobby(Request $request)
    {
      $userProfile = UserProfile::where('id_user', Auth::user()->id)->first();
      if($userProfile){
        $userProfile->hobby = $userProfile->hobby.','.$request->hobby;
        $userProfile->save();
      }else {
        $userProfileNew = new UserProfile;
        $userProfileNew->id_user = Auth::user()->id;
        $userProfileNew->hobby = $request->hobby;
        $userProfileNew->save();
      }

      return redirect()->back();
    }

    /**
     *  Store a newly created resource in storage.
     *
     * @return \Illuminate\Http\Response
     */
    public function delete_hobby(Request $request)
    {
      $userProfile = UserProfile::where('id_user', Auth::user()->id)->first();
      $hobby = explode(',', $userProfile->hobby);
      $hobby = array_diff($hobby, [$request->hobby]);
      $userProfile->hobby = implode(',', $hobby);
      $userProfile->save();

      return redirect()->back();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/User/Dashboard/DashboardTempatController.php
<?php

namespace App\Http\Controllers\User\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardTempatController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/user/dashboard/myhobby/create.blade.php
@extends('layouts.app')

@section('style')
<style>
@media (min-width: 992px){
  .page-dashboard {
      padding: 100px 0 100px 0;
  }

  .sidebar-dashboard {
      max-height: max-content;
  }

  .header-page {
    margin-bottom: 50px;
  }

  .btn-submit {
    padding: 7px;
  }
}
</style>

<link href="https://cdn.jsdelivr.net/npm/froala-editor@3.0.0/css/froala_editor.pkgd.min.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/froala-editor@3.0.0/js/froala_editor.pkgd.min.js"></script>
@stop

@section('content')
<div class="page-dashboard">
  <div class="container">
  	<div class="breadcrumbs-container breadcrumbs-top">
  	  <ul class="breadcrumbs min-list inline-list">
  	    <li class="breadcrumbs__item">
  	      <a href="index.html" class="breadcrumbs__link">
  	        <span class="breadcrumbs__title">Home</span>
  	      </a>
  	    </li>

  	    <li class="breadcrumbs__item">
  	      <a href="#" class="breadcrumbs__link">
  	        <span class="breadcrumbs__title">Dashboard</span>
  	      </a>
  	    </li>

        <li class="breadcrumbs__item">
  	      <a href="#" class="breadcrumbs__link">
  	        <span class="breadcrumbs__title">Berita</span>
  	      </a>
  	    </li>

  	    <li class="breadcrumbs__item">
  	      <span class="breadcrumbs__page c-gray">Tambah</span>
  	    </li>
  	  </ul><!-- .breadcrumbs -->
  	</div>
  	<h1 class="header-page">Tambah Berita</h1>
  	<div class="row">
  		<div class=" col-lg-4">
  			@include('layouts.partials')
  		</div>
  		<!-- end-col -->
  		<div class="col-lg-8">
        <div class="content-dashboard_wishlist dashboard-bg dashboard-pd">
          <div class="title-review">
            <h2>Berita</h2>
          </div>
          <div class="dashboard_edit-profile">
						<div class="content-dashboard_profile">
							<div class="row">
								<div class="col-md-12">
									<div class="profile_info">
										<div class="profile_form-login">
											<form action="{{route('admin.berita.store')}}" method="post" class="form-login"  enctype="multipart/form-data">
                        @csrf
												<h3 class="title_profile-info c-sale">Detail Berita</h3>
												<div class="profile-personal">
													<div class="row">
														<div class="col-md-12">
															<div class="form-login__input">
																<label class="label-login" for="login-name">Judul <span class="c-sale">*</span></label>
																<input type="text" name="judul" id="login-name" class="form-input input-border text-input">
															</div>
														</div>
                            <div class="form-login__input">
                              <div class="col-md-12">
                                <label class="label-login" for="login-name">Gambar Berita <span class="c-sale">*</span></label>
                                <input type="file" name="gambar" class="form-input input-border text-input">
                              </div>
                            </div>
														<div class="col-md-12">
															<div class="form-login__input">
																<label class="label-login"  for="login-country">Deskripsi</label>
                                <textarea id="example" name="deskripsi"></textarea>
															</div>
														</div>
                            <div class="col-md-12">
															<div class="form-login__input">
																<label class="label-login" for="login-name">Hobby <span class="c-sale">*</span></label>
																<select name="hobby[]" class="form-input input-border text-input" multiple>
                                  @foreach($hobby as $item)
                                  <option value="{{$item->nama}}">{{$item->nama}}</option>
                                  @endforeach
                                </select>
                                <p style="padding:5px;color:red">*Tekan Ctrl untuk memilih lebih dari 1</p>
															</div>
														</div>
                            <div class="col-md-12">
                              <div class="form-login__button">
                                <button type="submit" class="btn-submit btn-radius">Save Changes</button>
                              </div>
                            </div>
													</div>
												</div>
											</form>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
        </div>
  		</div>
  		<!-- end-col -->
  	</div>
  	<!-- end-row -->
  </div>
  <!-- end-container -->
</div>
@endsection

@section('script')
<script>
var editor = new FroalaEditor('#example', {
  toolbarButtons: {
    'moreText': {
      'buttons': ['bold', 'italic', 'underline']
    },
    'moreParagraph': {
      'buttons': ['alignLeft', 'alignCenter', 'formatOLSimple', 'alignRight', 'alignJustify', 'formatOL', 'formatUL', 'paragraphFormat', 'paragraphStyle', 'lineHeight', 'outdent', 'indent', 'quote']
    },
    'moreRich': {
      'buttons': ['insertImage']
    },
    'moreMisc': {
      'buttons': ['undo', 'redo', 'fullscreen', 'print', 'getPDF', 'spellChecker', 'selectAll', 'html', 'help'],
      'align': 'right',
      'buttonsVisible': 2
    }
  }
});
</script>
<style>

/* .fr-wrapper > div:first-child{
  display: none;
} */


/* .second-toolbar{
  display: none;
} */
</style>
@stop

resources/views/user/dashboard/myhobby/index.blade.php
@extends('layouts.app')

@section('style')
<style>
@media (min-width: 992px){
  .page-dashboard {
      padding: 100px 0 100px 0;
  }

  .sidebar-dashboard {
      max-height: max-content;
  }

  .header-page {
    margin-bottom: 50px;
  }

  .btn-submit {
    padding: 7px;
  }
}
</style>
@stop

@section('content')
<div class="page-dashboard">
  <div class="container">
  	<div class="breadcrumbs-container breadcrumbs-top">
  	  <ul class="breadcrumbs min-list inline-list">
  	    <li class="breadcrumbs__item">
  	      <a href="index.html" class="breadcrumbs__link">
  	        <span class="breadcrumbs__title">Home</span>
  	      </a>
  	    </li>

  	    <li class="breadcrumbs__item">
  	      <a href="#" class="breadcrumbs__link">
  	        <span class="breadcrumbs__title">Dashboard</span>
  	      </a>
  	    </li>

  	    <li class="breadcrumbs__item">
  	      <span class="breadcrumbs__page c-gray">My Profile</span>
  	    </li>
  	  </ul><!-- .breadcrumbs -->
  	</div>
  	<h1 class="header-page">Dashboard</h1>
  	<div class="row">
  		<div class=" col-lg-4">
  			@include('layouts.partials')
  		</div>
  		<!-- end-col -->
  		<div class="col-lg-8">
        <div class="content-dashboard_wishlist dashboard-bg dashboard-pd">
          <div class="title-review">
            <h2>My Hobby</h2>
          </div>
          <div class="list-my-booking">
            <div class="item-booking">
              <form action="{{route('user.hobby.store')}}" method="post">
                @csrf
                <button type="submit" class="btn-submit submit-footer btn-radius" style="float:right;height:40px">Tambah Hobby</button>
                <select name="hobby" class="form-input input-border text-input"  style="float:right;width:auto;height:40px;margin-right:20px">
                  @foreach($hobby as $item)
                  <option value="{{$item->nama}}">{{$item->nama}}</option>
                  @endforeach
                </select>
              </form>
              <h3 class="title-my-booking">List Hobby</h3>
              <div class="list-items__wrapp">
                @forelse($hobbyUser as $index => $item)
                <div class="list-items__wrapper d-lg-flex">
                  <div class="wishlist_wrapper d-flex">
                    <div class="wishlist_thubmail">
                      <a href="#"><img src="{{asset('assets/img/'.$item->gambar)}}" style="width:100px;height:100px;border-radius:50%" alt="tours"></a>
                    </div>
                    <div class="wishlist_detail">
                      <h3> <a href="tour-single.html" class="wishlist_title" style="line-height: 5;">{{$item->nama}}</a></h3>
                    </div>
                  </div>
                  <div class="wishlist_action" style="    padding-right: 10px;">
                    <div class="d-lg-flex justify-content-between" style="line-height:3">
                      <a class="wishlist-link" onclick="$('#destroy_hobby-{{$item->id}}').submit()" href="#" style="font-size:25px"><i class="fa fa-trash"></i></a>
                      <form id="destroy_hobby-{{$item->id}}" method="post" action="{{route('user.hobby.destroy', $item->id)}}">
                        @csrf
                        @method('DELETE')
                      </form>
                    </div>
                  </div>
                </div>
                @empty
                <div>
                  <h3 style="text-align:center">Tidak Ada Hobi Yang Anda Pilih</h3>
                </div>
                @endforelse
              </div>
            </div>
            <div class="pagination_tours-reviews center">
              <ul class="min-list inline-list">
                <li><a href="#" class="ion-ios-arrow-back"></a></li>
                <li class="active"><a href="#">1</a></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">...</a></li>
                <li><a href="#">15</a></li>
                <li><a href="#" class="ion-ios-arrow-forward"></a></li>
              </ul>
            </div>
          </div>
        </div>
  		</div>
  		<!-- end-col -->
  	</div>
  	<!-- end-row -->
  </div>
  <!-- end-container -->
</div>
@endsection

@section('script')
<script>
</script>
@stop